ballparktracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('', views.Home.as_view(), name='home'),
  path('about/', views.about, name='about'),
  path('stadiums/', views.stadiums_index, name='stadiums_index'),
  path('stadiums/<int:stadium_id>/', views.stadiums_detail, name='stadiums_detail'),
  path('stadiums/create/', views.StadiumCreate.as_view(), name='stadiums_create'),
  path('stadiums/<int:pk>/update/', views.StadiumUpdate.as_view(), name='stadiums_update'),
  path('stadiums/<int:pk>/delete/', views.StadiumDelete.as_view(), name='stadiums_delete'),
  path('stadiums/<int:stadium_id>/add_concession/', views.add_concession, name='add_concession'),
  path('accounts/signup/', views.signup, name='signup'),

]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.
SNACKS = (
  ('B', 'Beer'),
  ('S', 'Soda'),
  ('H', 'Hot Dog'),
  ('N', 'Nachos')
)

class Stadium(models.Model):
  name = models.CharField(max_length=50)
  location = models.CharField(max_length=100)
  description = models.TextField(max_length=250)
  user = models.ForeignKey(User, on_delete=models.CASCADE)

  def __str__(self):
    return self.name

  def get_absolute_url(self):
      return reverse("stadiums_detail", kwargs={"stadium_id": self.id})

class Concession(models.Model):
  date = models.DateField('Purchase Date')
  snack = models.CharField(
    max_length=1,
    choices=SNACKS,
    default=SNACKS[0][0]
    )
  stadium = models.ForeignKey(Stadium, on_delete=models.CASCADE)

  def __str__(self):
    return f"{self.get_snack_display()} on {self.date}"

  class Meta:
    ordering = ['-date']

main_app/forms.py
from django.forms import ModelForm
from .models import Concession

class ConcessionForm(ModelForm):
  class Meta:
    model = Concession
    fields = ['date', 'snack']

main_app/views.py
from django.shortcuts import redirect, render
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Stadium
from .forms import ConcessionForm
from django.contrib.auth.views import LoginView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin



# Create your views here.

class Home(LoginView):
  template_name = 'home.html'

def about(request):
  return render(request, 'about.html')

@login_required
def stadiums_index(request):
  stadiums = Stadium.objects.filter(user=request.user)
  return render(request, 'stadiums/index.html', {'stadiums':stadiums})

@login_required
def stadiums_detail(request, stadium_id):
  stadium = Stadium.objects.get(id=stadium_id)
  concession_form = ConcessionForm()
  return render(request, 'stadiums/detail.html', { 'stadium':stadium, 'concession_form': concession_form })

class StadiumCreate(LoginRequiredMixin, CreateView):
  model = Stadium
  fields = ['name', 'location', 'description']
  success_url = '/stadiums/'

  def form_valid(self,form):
    form.instance.user = self.request.user
    return super().form_valid(form)

class StadiumUpdate(LoginRequiredMixin, UpdateView):
  model = Stadium
  fields = ['description', 'location']

class StadiumDelete(LoginRequiredMixin, DeleteView):
  model = Stadium
  success_url = '/stadiums/'

@login_required
def add_concession(request, stadium_id):
  form = ConcessionForm(request.POST)
  if form.is_valid():
    new_concession= form.save(commit=False)
    new_concession.stadium_id = stadium_id
    new_concession.save()
  return redirect('stadiums_detail', stadium_id=stadium_id)

def signup(request):
  error_message = ''
  if request.method == 'POST':
    form = UserCreationForm(request.POST)
    if form.is_valid():
      user = form.save()
      login(request, user)
      return redirect('stadiums_index')
    else:
      error_message = 'Invalid sign up - try again'
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'signup.html', context)

main_app/templates/about.html
{% extends 'base.html' %}

{% block content %}
<h1>About the Ballpark Tracker</h1>
<hr />
<p class="page-content">
  You can create, follow, write descriptions and track any concessions you purchase with this Ballpark Tracker app!
</p>

{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link
    rel="shortcut icon"
    type="image/png"
    href="{% static 'images/stadium.svg' %}"
  >
  <title>Ballpark Tracker</title>
  <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
  {% block head %}
  {% endblock %}
</head>
<body>
  <header>
    <a href="/">
      <img 
        src="{% static 'images/MLB.svg' %}"
        alt="The Ballpark Logo"
      >
    </a>
    <div class="header-logo-container">
    </div>
    <nav>
      <ul>
        {% if user.is_authenticated %}
        <li><a href="{% url 'stadiums_index' %}">Stadiums</a></li>
        <li><a href="{% url 'stadiums_create' %}">Add Stadiums</a></li>
        <li><a href="{% url 'about' %}">About</a></li>
        <li><a href="{% url 'logout' %}">Log out</a></li>
        {% else %}
        <li><a href="{% url 'about' %}">About</a></li>
        <li><a href="{% url 'home' %}">Login</a></li>
        <li><a href="{% url 'signup' %}">Sign Up</a></li>
      {% endif %}
      </ul>
    </nav>
  </header>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

main_app/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}"/>
{% endblock %}

{% block content %}

<section class="logo-container">
  <div class="stadium-container">
    <img src="{% static 'images/Baseball.svg' %}" alt="The Ballpark Tracker" />
  </div>
</section>
{% if not user.is_authenticated %}
<section>
  <form action="{% url 'home' %}" method="post" class="login">
    <h1>Login</h1>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="hidden" name="next" value="{{ next }}">
    <button type="submit" class="btn submit">Login</button>
  </form>
</section>
{% endif %}

{% endblock %}

main_app/templates/main_app/stadium_confirm_delete.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="page-header">
  <h1>Delete Stadium?</h1>
  <img src="{% static 'images/Park.svg' %}" alt="A Stadium"/>
</div>
<h2>Are you sure you want to delete {{ stadium.name }}?</h2>

<form action="" method="POST" class="form">
  {% csrf_token %}
  <a 
    href="{% url 'stadiums_detail' stadium.id %}" 
    class="btn secondary"
  >
    Cancel
  </a>
  <button type="submit" class="btn danger">Yes - Delete!</button>
</form>

{% endblock %}

main_app/templates/main_app/stadium_form.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/form.css' %}"/>
{% endblock %}

{% block content %}

<div class="page-header">
  {% if stadium %}
  <h1>Edit {{ stadium.name }}</h1>
  {% else %}
  <h1>Add a Stadium</h1>
  {% endif %}
  <img src="{% static 'images/Park.svg' %}" alt="A stadium"/>
</div>
<form action="" method="post" class="form-container">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <button type="submit" class="btn submit">Submit!</button>
</form>

{% endblock %}

main_app/templates/signup.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/form.css' %}"/>
{% endblock %}

{% block content %}

<div class="page-header">
  <h1>Sign Up</h1>
  <img src="{% static 'images/Baseball.svg' %}" alt="A baseball"/>
</div>
{% if error_message %}
  <p class="red-text">{{ error_message }}</p>
{% endif %}
<form action="" method="post" class="form-container" autocomplete="off">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <button type="submit" class="btn submit">Submit!</button>
</form>

{% endblock %}

main_app/templates/stadiums/detail.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link 
  href="https://cdn.jsdelivr.net/npm/mc-datepicker/dist/mc-calendar.min.css" 
  rel="stylesheet" 
/>
<link rel="stylesheet" href="{% static 'css/mcdp.css' %}">
<script 
  src="https://cdn.jsdelivr.net/npm/mc-datepicker/dist/mc-calendar.min.js"
>
</script>
<link 
  rel="stylesheet" 
  type="text/css" 
  href="{% static 'css/stadiums/stadium-detail.css' %}"
/>
<script defer src="{% static 'js/stadium-detail.js' %}"></script>
{% endblock %}

{% block content %}

<section class="stadium-container">
  <div class="stadium-img">
    <img 
      src="{% static 'images/Major.svg' %}" 
      alt="A stadium"
    >
  </div>
  <div class="stadium-details">
    <h1>{{ stadium.name }}</h1>
    <p>This Stadium is located in {{ stadium.location }}</p>
    <p>{{ stadium.description }}</p>
    <div class="stadium-actions">
      <a href="{% url 'stadiums_update' stadium.id %}" class="btn warn">Edit</a>
      <a href="{% url 'stadiums_delete' stadium.id %}" class="btn danger">Delete</a>
    </div>
  </div>
</section>
<div class="concessions-container">
  <section class="concessions">
    <div class="subsection-title">
      <h2>Concessions</h2>
      <img 
        src="{% static 'images/Beer.svg' %}" 
        alt="A beer"
      />
      <img 
      src="{% static 'images/HotDog.svg' %}" 
      alt="A hotdog"
    />
    </div>
    <h3>Add a Concession</h3>
    <form
      action="{% url 'add_concession' stadium.id %}"
      method="post" 
      class="subsection-content"
    >
      {% csrf_token %}
      {{ concession_form.as_p }}
      <button type="submit" class="btn submit">Add Concession</button>
    </form>
    <h3>Past Concessions</h3>
    {% if stadium.concession_set.all.count %}
    <table>
      <thead>
        <tr><th>Date</th><th>Snack</th></tr>
      </thead>
      <tbody>
        {% for concession in stadium.concession_set.all %}
          <tr>
            <td>{{ concession.date }}</td>
            <td>{{ concession.get_snack_display }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    {% else %}
    <div class="subsection-content">
      <p>{{stadium.name}} Your Concessions are empty. Quick grab a beer and log it!</p>
    </div>
    {% endif %}
  </section>
</div>

{% endblock %}

main_app/templates/stadiums/index.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link 
  rel="stylesheet"
  type="text/css"
  href="{% static 'css/stadiums/stadium-index.css' %}"
/>
{% endblock %}

{% block content %}

<section class="page-header">
  <h1>Stadium List</h1>
  <img src="{% static 'images/Park.svg' %}" alt="A cool stadium" />
</section>

<section class="card-container">
  {% for stadium in stadiums %}
    <div class="card">
      <a href="{% url 'stadiums_detail' stadium.id %}"
      <div class="card-content">
        <div class="card-img-container">
          <img 
            src="{% static 'images/Baseball Stadium.svg' %}" 
            alt="A stadium"
          >
        </div>
        <h2 class="card-title">{{ stadium.name }}</h2>
        <p>This is located in {{ stadium.location }}</p>
        <p><small>{{ stadium.description }}</small></p>
      </div>
      </a>
    </div>
  {% endfor %}
</section>

{% endblock %}